# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: nextjs-app/package-lock.json
    - name: Install Next.js dependencies
      run: |
        cd nextjs-app
        npm ci
    - name: Build Next.js application
      run: |
        cd nextjs-app
        npm run build
    - name: Copy Next.js build to docs
      run: |
        rm -rf docs/*
        cp -r nextjs-app/out/* docs/
        touch docs/.nojekyll
    - name: Commit files
      run: |
         git config --local user.email "erbanku@gmail.com"
         git config --local user.name "Cactus"
         git pull
         git add README.md
         git add bing-wallpaper.md
         git add picture/*
         git add docs/*
         git commit -m "update readme.md and rebuild site"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: main
